sudo: false
language: python
python:
  - '2.7'
  - '3.3'
  - '3.4'
matrix:
  allow_failures:
    - python: '2.7'
install:
  - pip install flake8 'nose>=1.3.0' coverage coveralls
  - python setup.py install
  - pip install 'Sphinx>=1.2.2' sphinx_rtd_theme
script:
  - flake8 .
  - python setup.py nosetests
  - python setup.py build_sphinx
after_success:
  coveralls
